source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'MWPhotoBrowser_Example-Swift' do
  pod "MWPhotoBrowser", :path => "../"
  # pod 'MWPhotoBrowser', '2.1.2'
end
